import React from 'react';
import { Sparkles, ArrowRight, Lightbulb, CheckCircle2, Shield, Users, Clock } from 'lucide-react';
import { Card } from '../common/Card';
import { Badge } from '../common/Badge';

export const RecommendationPanel = ({ recommendations = [] }) => {
  const getCategoryIcon = (category) => {
    switch (category) {
      case 'Team Staffing':
        return <Users className="w-4 h-4 text-brand-500 shrink-0" />;
      case 'Scope Optimization':
        return <Lightbulb className="w-4 h-4 text-amber-500 shrink-0" />;
      case 'Security & Compliance':
        return <Shield className="w-4 h-4 text-rose-500 shrink-0" />;
      case 'Delivery Schedule':
        return <Clock className="w-4 h-4 text-purple-500 shrink-0" />;
      default:
        return <Sparkles className="w-4 h-4 text-emerald-500 shrink-0" />;
    }
  };

  const getImpactBadge = (impact) => {
    switch (impact) {
      case 'Critical':
        return 'danger';
      case 'High':
        return 'warning';
      default:
        return 'brand';
    }
  };

  return (
    <Card className="p-6 bg-white dark:bg-navy-900 border-slate-200/90 dark:border-slate-800 space-y-4">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 pb-3 border-b border-slate-100 dark:border-slate-800">
        <div>
          <h3 className="text-base font-bold text-slate-900 dark:text-white flex items-center gap-2">
            <Sparkles className="w-4 h-4 text-brand-500" />
            Engineering & Strategic Recommendations
          </h3>
          <p className="text-xs text-slate-400">
            Automated recommendations generated by the EstimateAI engine to optimize cost and time-to-market.
          </p>
        </div>
        <Badge variant="purple" size="sm">
          {recommendations.length} Actionable Advice
        </Badge>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-3.5">
        {recommendations.map((rec, i) => (
          <div
            key={i}
            className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800/40 border border-slate-200/70 dark:border-slate-800 space-y-2 text-xs flex flex-col justify-between"
          >
            <div>
              <div className="flex items-center justify-between gap-2 mb-1.5">
                <div className="flex items-center gap-1.5 font-bold text-slate-900 dark:text-white">
                  {getCategoryIcon(rec.category)}
                  <span>{rec.title}</span>
                </div>
                <Badge variant={getImpactBadge(rec.impact)} size="sm">
                  {rec.impact} Impact
                </Badge>
              </div>

              <p className="text-slate-600 dark:text-slate-400 leading-relaxed pl-5">
                {rec.description}
              </p>
            </div>

            <div className="pt-2 pl-5 text-[11px] font-mono text-slate-400 flex items-center gap-1">
              <span>Category:</span>
              <strong className="text-slate-600 dark:text-slate-300 font-semibold">{rec.category}</strong>
            </div>
          </div>
        ))}
      </div>
    </Card>
  );
};
